version: '3.8'

services:
  db:
    image: library/postgres:11-alpine
    container_name: petdb
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "15432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
